# Site settings
title: Unexpected error at line 0.
email: richard AT newmanworks DOT com
description: > # this means to ignore newlines until "baseurl:"
  Yeah, I tried that.  Or maybe not.

  To tell you the truth, I forget.
  
  Maybe that's why I write it down.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rdnewman.github.io" # the base hostname & protocol for your site
twitter_username: rdnewman
github_username:  rdnewman

# Build settings
markdown: kramdown
