# Site settings
title: Unexpected error at line 0.
description: Unexpected error at line 0.
intro:
logo:     logo.png
paginate: 8
#timezone: America/Boise
disqus_shortname: rdnewmangithubio

# URL: comment out one or the other
#url: "http://rdnewman.github.io"  # PRODUCTION: the base hostname & protocol for your site
url: "http://127.0.0.1:4000"      # LOCAL:      the base hostname & protocol for your site

baseurl: "" # the subpath of your site, e.g. /blog/

# Owner/author information
owner:
  name:           Richard Newman
  # avatar:         <avatar-image-link>
  #email:          richard@newmanworks.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        rdnewman
  github:         rdnewman
  stackexchange:  rdnewman
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    rdnewman

# Build settings
excerpt_separator: <!--more-->

markdown: redcarpet
highlighter: pygments

sass:
  sass_dir: _sass
  style: :compressed
